apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/service.yaml
- manifests/deployment.yaml
- manifests/ingress.yaml
- manifests/configmap.yaml
images:
- name: LOG_OUTPUT/IMAGE
  newName: 3nd3r1/log-output
  newTag: b5f852f82c08460067699e5d9ae86d34a7ac9e7c
