apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/service.yaml
- manifests/deployment.yaml
- manifests/ingress.yaml
- manifests/configmap.yaml
images:
- name: LOG_OUTPUT/IMAGE
  newName: 3nd3r1/log-output
  newTag: 6780d8277e4c3e77a0e54c9377c2caad9d7a5628
