apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/service.yaml
- manifests/deployment.yaml
- manifests/ingress.yaml
- manifests/configmap.yaml
images:
- name: LOG_OUTPUT/IMAGE
  newName: 3nd3r1/log-output
  newTag: b1121d0e2a4d7ec62d19c45927a3a193cfdec115
