---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  labels:
    project: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: log-output-cm
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: main
          image: 3nd3r1/log-output:latest
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "100Mi"
              cpu: "10m"
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-cm
                  key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/data
