---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummysite-controller-role
  namespace: system
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "patch", "update", "get", "list", "delete", "watch"]
  - apiGroups: ["stable.dwk.stable.dwk"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
