---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: 3nd3r1/ping-pong:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ping-pong-database-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ping-pong-database-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: "ping-pong-database-svc"
            - name: POSTGRES_PORT
              value: "5432"
