---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: log-output-ping-pong-pvc
      containers:
        - name: ping-pong
          image: 3nd3r1/ping-pong:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data-volume
              mountPath: /usr/src/app/data
