---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  labels:
    project: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: PING_PONG/IMAGE
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8080
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "100Mi"
              cpu: "10m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ping-pong-database-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ping-pong-database-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: "ping-pong-database-svc"
            - name: POSTGRES_PORT
              value: "5432"
