---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-database-svc
  labels:
    project: ping-pong
spec:
  type: ClusterIP
  selector:
    app: ping-pong-database
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ping-pong
  labels:
    project: ping-pong
spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: PING_PONG/IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: ping-pong-database-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: ping-pong-database-secret
            - name: POSTGRES_HOST
              value: ping-pong-database-svc
            - name: POSTGRES_PORT
              value: "5432"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 10m
              memory: 100Mi
