apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/service.yaml
- manifests/deployment.yaml
- manifests/statefulset.yaml
images:
- name: PING_PONG/IMAGE
  newName: 3nd3r1/ping-pong
  newTag: e51cda8025a4ccc7b99d16176e3584093ac8a2ef
