---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-project-wikipedia-todo-cronjob
  labels:
    project: todo-project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: wikipedia
              image: curlimages/curl:8.9.1
              command: ["sh", "-c"]
              args:
                - |
                  WIKI_URL=$(curl -s -I https://en.wikipedia.org/wiki/Special:Random | grep -i '^location:' | sed 's/location: //' | sed 's/\r//');
                  if [ -n "$WIKI_URL" ]; then
                    PAYLOAD=$(printf '{"title":"Read %s"}' "$WIKI_URL");
                    echo "Sending payload: $PAYLOAD";
                    RESPONSE=$(curl -s -X POST ${TODO_BACKEND_URL}/todos -H "Content-Type: application/json" -d "$PAYLOAD"});
                    echo "Response from server: $RESPONSE";
                  else
                    echo "Failed to fetch random Wikipedia article";
                  fi
              env:
                - name: TODO_BACKEND_URL
                  value: http://todo-project-svc:8080/api
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-project-backup-cronjob
  labels:
    project: todo-project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: gcp-sa-key-file
              secret:
                secretName: todo-project-backup-agent-secret
                items:
                  - key: sa-private-key.json
                    path: sa-private-key.json
          containers:
            - name: backup
              image: TODO_PROJECT_BACKUP_AGENT/IMAGE
              volumeMounts:
                - name: gcp-sa-key-file
                  mountPath: /tmp/sa-private-key.json
                  subPath: sa-private-key.json
                  readOnly: true
              env:
                - name: GCP_SA_KEY_FILE
                  value: /tmp/sa-private-key.json
                - name: GCP_SA_NAME
                  valueFrom:
                    secretKeyRef:
                      name: todo-project-backup-agent-secret
                      key: GCP_SA_NAME
                - name: GCP_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: todo-project-backup-agent-secret
                      key: GCP_BUCKET_NAME
                - name: POSTGRES_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: todo-project-database-secret
                      key: POSTGRES_DATABASE
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: todo-project-database-secret
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: todo-project-database-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_HOST
                  value: todo-project-database-svc
                - name: POSTGRES_PORT
                  value: "5432"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
          restartPolicy: OnFailure
