---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-project-data-pvc
  labels:
    project: todo-project
spec:
  storageClassName: todo-project-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
