---
apiVersion: v1
kind: Service
metadata:
  name: todo-project-backend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
