---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-project-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/3nd3r1/devops-with-kubernetes
    path: todo-project/manifests/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
