---
services:
  backend:
    image: golang:1.22
    container_name: todo-project-backend
    environment:
      - PORT=3001
    ports:
      - 127.0.0.1:3001:3001
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: ["go", "run", "./cmd/app/main.go"]
  frontend:
    image: node:21
    container_name: todo-project-frontend
    environment:
      - PORT=3000
      - NEXY_PUBLIC_BACKEND_URL=http://backend:3001/api
      - NEXT_PUBLIC_IMAGENATOR_URL=http://localhost:3002/imagenator/image
    ports:
      - 127.0.0.1:3000:3000
    links:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: ["npm", "run", "dev"]
  imagenator:
    image: golang:1.22
    container_name: todo-project-imagenator
    environment:
      - PORT=3002
      - DATA_DIR=/usr/src/app/data
    ports:
      - 127.0.0.1:3002:3002
    volumes:
      - ./imagenator:/usr/src/app
    working_dir: /usr/src/app
    command: ["go", "run", "./cmd/app/main.go"]
