---
services:
  backend:
    image: golang:1.22
    container_name: todo-project-backend
    environment:
      - PORT=3001
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    links:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: ["go", "run", "./cmd/app/main.go"]

  frontend:
    image: node:21
    container_name: todo-project-frontend
    environment:
      - PORT=3000
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: ["npm", "run", "dev"]

  imagenator:
    image: golang:1.22
    container_name: todo-project-imagenator
    environment:
      - PORT=3002
      - DATA_DIR=/usr/src/app/data
    volumes:
      - ./imagenator:/usr/src/app
    working_dir: /usr/src/app
    command: ["go", "run", "./cmd/app/main.go"]

  postgres:
    image: postgres
    container_name: todo-project-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:1.21
    container_name: todo-project-nginx
    ports:
      - 127.0.0.1:3000:80
    links:
      - frontend
      - backend
      - imagenator
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
