---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/deployment.yaml
  - manifests/cronjob.yaml
  - manifests/statefulset.yaml
  - manifests/persistentvolumeclaim.yaml
images:
  - name: TODO_PROJECT_BACKEND/IMAGE
    newName: 3nd3r1/todo-project-backend
  - name: TODO_PROJECT_FRONTEND/IMAGE
    newName: 3nd3r1/todo-project-frontend
  - name: TODO_PROJECT_IMAGENATOR/IMAGE
    newName: 3nd3r1/todo-project-imagenator
