---
- op: replace
  path: /spec/rules/0/http/paths/0/path
  value: /staging/api
- op: replace
  path: /spec/rules/0/http/paths/1/path
  value: /staging
- op: replace
  path: /spec/rules/0/http/paths/2/path
  value: /staging/imagenator
- op: replace
  path: /metadata/annotations/traefik.ingress.kubernetes.io/router.middlewares
  value: staging-staging-todo-project-stripprefix-middleware@kubernetescrd
