apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: backup-cronjob-patch.yaml
- path: wiki-cronjob-patch.yaml
  target:
    kind: CronJob
    name: todo-project-wikipedia-todo-cronjob
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: todo-project-broadcaster-dep
- path: rollout-patch.yaml
  target:
    kind: Rollout
    name: todo-project-dep
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: todo-project-ingress

namePrefix: staging-

images:
- name: TODO_PROJECT_BACKEND/IMAGE
  newName: 3nd3r1/todo-project-backend
  newTag: e51cda8025a4ccc7b99d16176e3584093ac8a2ef
- name: TODO_PROJECT_BACKUP_AGENT/IMAGE
  newName: 3nd3r1/todo-project-backup-agent
  newTag: e51cda8025a4ccc7b99d16176e3584093ac8a2ef
- name: TODO_PROJECT_BROADCASTER/IMAGE
  newName: 3nd3r1/todo-project-broadcaster
  newTag: e51cda8025a4ccc7b99d16176e3584093ac8a2ef
- name: TODO_PROJECT_FRONTEND/IMAGE
  newName: 3nd3r1/todo-project-frontend
  newTag: e51cda8025a4ccc7b99d16176e3584093ac8a2ef
- name: TODO_PROJECT_IMAGENATOR/IMAGE
  newName: 3nd3r1/todo-project-imagenator
  newTag: e51cda8025a4ccc7b99d16176e3584093ac8a2ef
