apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    project: ping-pong
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: ping-pong
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: ping-pong-database-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: ping-pong-database-secret
            - name: POSTGRES_HOST
              value: ping-pong-database-svc
            - name: POSTGRES_PORT
              value: "5432"
          image: PING_PONG/IMAGE
          name: ping-pong
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: 10m
              memory: 100Mi
---

