---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-ping-pong-pvc
spec:
  storageClassName: log-output-ping-pong-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
