---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-project-data-pvc
  namespace: project
spec:
  storageClassName: todo-project-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
