---
- op: replace
  path: /spec/template/spec/containers/1/env/3/value
  value: prod-todo-project-database-svc
- op: replace
  path: /spec/template/spec/volumes/1/persistentVolumeClaim/claimName
  value: prod-todo-project-data-pvc
- op: replace
  path: /spec/template/spec/containers/1/env/5/value
  value: nats://prod-todo-project-nats:4222
- op: replace
  path: /spec/strategy/canary/steps/2/analysis/templates/0/templateName
  value: prod-cpu-limit-monitor
- op: add
  path: /spec/strategy/canary/steps/2/analysis/args
  value:
    - name: namespace
      value: production
