---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project-frontend
  template:
    metadata:
      labels:
        app: todo-project-frontend
    spec:
      containers:
        - name: main
          image: 3nd3r1/todo-project-frontend:latest
          ports:
            - containerPort: 3000
