---
apiVersion: v1
kind: Service
metadata:
  name: todo-project-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: todo-project-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
