---
name: Log Output - Build and Publish

on:
  push:
    branches:
      - main

env:
  LOG_OUTPUT_IMAGE: log-output

jobs:
  build-publish:
    name: Build, Publish, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Build
        working-directory: ./log-output
        run: |-
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/${LOG_OUTPUT_IMAGE}:${GITHUB_SHA}" -f ./build/Dockerfile .

      - name: Publish
        run: |-
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${LOG_OUTPUT_IMAGE}:${GITHUB_SHA}"

      - name: Update image in kustomization.yaml
        working-directory: ./log-output
        run: |-
          kustomize edit set image LOG_OUTPUT/IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${LOG_OUTPUT_IMAGE}:${GITHUB_SHA}

      - name: Commit kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: "./log-output/kustomization.yaml"
          fetch: true
          pull: "--rebase --autostash"
          message: uplifted log-ouput to ${{ github.sha }}
