---
name: Ping Pong - Build and Publish

on:
  push:

env:
  PING_PONG_IMAGE: ping-pong

jobs:
  build-publish:
    name: Build, Publish, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Build
        working-directory: ./ping-pong
        run: |-
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/${PING_PONG_IMAGE}:${GITHUB_SHA}" -f ./build/Dockerfile .

      - name: Publish
        run: |-
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${PING_PONG_IMAGE}:${GITHUB_SHA}"

      - name: Update image in kustomization.yaml
        working-directory: ./ping-pong
        run: |-
          kustomize edit set image PING_PONG/IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${PING_PONG_IMAGE}:${GITHUB_SHA}

      - name: Commit kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: "./ping-pong/kustomization.yaml"
          fetch: true
          pull: "--rebase --autostash"
          message: uplifted ping-pong to ${{ github.sha }}
