---
name: Todo Project - Production

on:
  push:
    tags:
      - '**'

env:
  BACKEND_IMAGE: todo-project-backend
  FRONTEND_IMAGE: todo-project-frontend
  IMAGENATOR_IMAGE: todo-project-imagenator
  BACKUP_AGENT_IMAGE: todo-project-backup-agent
  BROADCASTER_IMAGE: todo-project-broadcaster
  TAG: ${{ github.ref_name }}

jobs:
  build-publish:
    name: Build, Publish, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Build
        working-directory: ./todo-project
        run: |-
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/${BACKEND_IMAGE}:${TAG}" -f ./backend/build/Dockerfile ./backend
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/${FRONTEND_IMAGE}:${TAG}" -f ./frontend/build/Dockerfile ./frontend
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/${IMAGENATOR_IMAGE}:${TAG}" -f ./imagenator/build/Dockerfile ./imagenator
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/${BACKUP_AGENT_IMAGE}:${TAG}" -f ./backup-agent/build/Dockerfile ./backup-agent
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/${BROADCASTER_IMAGE}:${TAG}" -f ./broadcaster/build/Dockerfile ./broadcaster

      - name: Publish
        run: |-
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${BACKEND_IMAGE}:${TAG}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${FRONTEND_IMAGE}:${TAG}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${IMAGENATOR_IMAGE}:${TAG}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${BACKUP_AGENT_IMAGE}:${TAG}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/${BROADCASTER_IMAGE}:${TAG}"

      - name: Update image in kustomization.yaml
        working-directory: ./todo-project/manifests/overlays/prod
        run: |-
          kustomize edit set image TODO_PROJECT_BACKEND/IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${BACKEND_IMAGE}:${TAG}
          kustomize edit set image TODO_PROJECT_FRONTEND/IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${FRONTEND_IMAGE}:${TAG}
          kustomize edit set image TODO_PROJECT_IMAGENATOR/IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${IMAGENATOR_IMAGE}:${TAG}
          kustomize edit set image TODO_PROJECT_BACKUP_AGENT/IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${BACKUP_AGENT_IMAGE}:${TAG}
          kustomize edit set image TODO_PROJECT_BROADCASTER/IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${BROADCASTER_IMAGE}:${TAG}

      - name: Commit kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: "./todo-project/manifests/overlays/prod/kustomization.yaml"
          fetch: true
          pull: "--rebase --autostash origin main"
          push: "origin HEAD:main"
          message: "uplifted todo-project-production to ${{ github.ref_name }}"
